// AUTO-GENERATED by sync-content-truth.mjs from CONTENT-TRUTH.md — DO NOT EDIT BY HAND.
// Offline snapshot of the MCP server verified knowledge (live source = Cloudflare KV).
// Used ONLY if KV is briefly unreachable. Regenerated on every deploy, so it cannot drift.
export const MCP_KNOWLEDGE_FALLBACK = `SEAWORTHY VERIFIED KNOWLEDGE (generated from CONTENT-TRUTH.md, source of truth, as of 2026-07-20).
Published, hedged, general information, never a recommendation for an individual. Use "as of 2026",
"typically", "in our placement experience". Route individual/carrier decisions to a quote or advisor.
Do not invent facts beyond this material.

## 2. Core concepts

### Own-occupation (the single most important provision)
- A **true own-occupation** definition pays total-disability benefits if you cannot perform the material
 and substantial duties of **your own occupation, even if you choose to work in another occupation** and
 keep earning.
- **What decides a CLAIM:** (1) the **definition type** being true
 own-occupation (not modified/transitional, which stop paying once you work elsewhere; not any-occupation,
 which pays only if you cannot work at all), applied to (2) the **material and substantial duties of your
 occupation at the time disability begins**: "your occupation" = the work you were actually doing when
 disability started. The claim is measured against your real duties at disability, NOT against the class you
 were underwritten at.
- **Occupation classification at underwriting is a DIFFERENT lever** (do not conflate with claim
 determination). It sets your occupation CLASS = premium + which definitions/riders/limits are available,
 and documents your full income so the benefit is sized right. It does NOT by itself decide whether a claim
 pays. So: "get classified correctly + document real income" is about price, limits, and benefit size; the
 claim standard is your occupation at the time of disability. For CRNAs the legitimate role of classification =
 occupation class + documenting full procedural income so the benefit is sized right; it never decides the claim.
- **Contracts are written in general terms by design.** In our review of all five majors, **none name a
 specialty like "anesthesia" or list duties.** Each measures disability against "your occupation"/"your
 specialty where further defined" at the start of disability. So what decides a claim is the **definition
 type + your real occupation/duties at the time of disability**, not any keyword in the contract.

### Occupation class
- The carrier's risk tier for a job. It **mainly drives premium** (and, at some carriers, which definitions/
 riders are available). It does **not** by itself decide whether a claim pays. Aim for the best class a
 carrier will assign to the actual occupation.

### Group vs. individual
- An **individual** own-occ policy is **indemnity**: it pays its stated monthly benefit regardless of other
 coverage. **Group LTD / association plans** are the ones that coordinate/offset (Social Security, other
 income) and cap the benefit. Group own-occ is usually time-limited (~24 months) then switches to an
 any-occupation test. Coordination across sources happens at **underwriting** (issue & participation
 limits), not by individual policies offsetting each other.

### Elimination period / benefit period
- Dominant placed structure: **90-day elimination period, to-age-65 benefit period.**

### Claim-time benefit calc
- **Total disability** pays the fixed monthly benefit issued; the carrier does **not** recalculate
 pre-disability earnings at claim. Income is verified at **underwriting**.
- **Residual** uses prior earnings; carriers protect against a single weak year (Principal uses the best
 two of the prior three calendar years). **Passive/unearned income** (investment, dividends, rent,
 royalties, passive equity distributions) is excluded from "income" and does not offset a total benefit
 (e.g., MassMutual: income "does not include Unearned Income").

---

## 3. Carriers: the five majors

Carrier-neutral: every quote is run across all five and compared on occupation class, own-occ language,
riders, exclusions, and premium, not price alone. Classes are revised periodically; a current quote is
the only reliable read. ("as of 2026")

| Carrier | CRNA occ class | Own-occ for a CRNA | Residual threshold | M/N + substance |
|---|---|---|---|---|
| **Guardian** Provider Choice (18ID) | 3M | TRUE, in base ("Enhanced True Own Occupation"). MD/DO procedural enhancement is physician-only, NOT CRNAs. | 15% | **For a CRNA: 24-mo limitation REQUIRED**: nurse anesthetists are in Guardian's high-risk group (with anesthesiology/ER/pain-mgmt/general dentistry, pharmacists and pharmacy technicians, certified anesthesiology assistants, and dental anesthesiologists) for which the cap is mandatory. The "no cap by default" applies to MOST OTHER occupations only (and not in CA). |
| **Principal** Income Protector (ICC22-800 / 750 CA-NY) | 2M+ | **TRUE** (Seaworthy always quotes the True Own Occupation definition, so it always functions true own-occ; treat as true own-occ; do NOT reopen base/upgrade or CA/NY nuance). | 15% (recovery at 20%) | **Occupation-class specific:** most med/dental can CHOOSE full M/N or a 24-mo limitation (≤10% discount) when own-occ is selected; 24-mo REQUIRED for ER, anesthesiology, pain-mgmt, **nurse anesthetists (CRNA)**, anesthesiology assistants, pharmacists (+ residents declaring these); full-coverage option not available in CA & NY (all cases), FL (single-life), VT (rider unavailable), TX (variation). (So "mandatory" is right for CRNAs; "optional" for most others.) |
| **MassMutual** Radius Choice (ICC15-XLIS-RC) | **4A** (publicly; upgraded from 3A in 2024) | TRUE via the **Own Occupation Rider** | 15% | 24-mo cap built in; removable via Max Benefit Period Endorsement (+~15%, NOT in CA); substance grouped |
| **The Standard** Platinum Advantage | **2P** | **NOT true own-occ for a CRNA**: 2P sits below the 3A/3P/3D the Own Occupation Rider requires; base "Regular Occupation" pays full benefits only while not working another occupation (residual still applies) | 20% | 24-mo limitation; REQUIRED for class 2P |
| **Ameritas** DInamic Cornerstone (form 4601NC; drop the unverified "ICC21" prefix) | **3M**, same tier as Guardian, a notch below MassMutual's 4A, so **MassMutual usually prices below Ameritas for a CRNA** | TRUE in the base definition | 15% | 24-mo cap REQUIRED at a CRNA's 3M class (and for anesthesiology/ER/OB-GYN and all GR policies); classes 6M-4M can instead choose full-benefit-period M/N (cap election earns a 10% discount); the limitation carves out dementia (Alzheimer's, stroke-related), paid as ordinary sickness; substance grouped |

- **Own-occ summary:** all five major carriers can be written as true own-occupation for most
 professions. How they deliver it differs: Guardian and Ameritas in the base definition; MassMutual and
 Principal via their own-occupation definition or rider; The Standard via a rider whose availability depends
 on occupation class. Exceptions are **class-based, not carrier-based**. For a CRNA specifically, The
 Standard's Own Occupation Rider is not available (CRNA = 2P, below the 3A/3P/3D threshold), so a CRNA's
 Standard policy is not true own-occ.
- **CRNA carrier-count rule:** four of the five major
 carriers write true own-occupation for a CRNA; The Standard does not (2P sits below the 3A/3P/3D threshold its
 Own Occupation Rider requires, and its base "Regular Occupation" definition pays full benefits only while not
 working in another occupation). Any statement to a CRNA about carriers and own-occupation must state this
 exception; never tell a CRNA that all five majors offer true own-occupation.
- **Underwriting flexibility (in our experience):**
 Most flexible to most conservative: **Principal > The Standard > MassMutual > Ameritas > Guardian.**
 Principal is the easiest to negotiate with (financial + medical); **Guardian is the strictest/most
 conservative.** Individual cases vary.
- **Exclusion/rating removal:** In our experience, at issue we negotiate for ratings/exclusions
 to be reconsiderable, with strong success getting them removed, commonly about 2 years after issue once a
 clean interval passes, so an exclusion may be reconsidered later rather than being permanent.

### Carrier operational / underwriting-process facts
- **Ameritas pricing:** competitive. Ameritas' real, verified differentiators are the points below
 plus its conservative underwriting.
- **Ameritas BOE limit = $100,000/month** (Business Overhead Expense), the highest BOE limit of the carriers we place; the
 others cap **roughly $50,000 to $60,000** (Guardian's Overhead Expense reaches $60,000/mo, 12-month, top
 classes).
- **Online medical history interview.** All five majors now offer an
 online medical interview. MassMutual recently moved from the required phone interview to its
 online Client Medical Interview (CMI), so it is no longer the lone phone-only
 holdout.
- **Ameritas mini-exam waiver:** Effective June 13, 2026, Ameritas eliminates the paramedical mini-exam (blood and urine testing, height, weight, blood pressure, pulse) for fully underwritten individual DI and BOE applicants age 50 and under, regardless of benefit amount, in all states except California traditional underwriting. With this, Ameritas joins MassMutual, Principal, and The Standard in waiving the exam for under-50 applicants (four of the five majors; Guardian is the lone holdout), reducing application friction for younger, healthy buyers.
- **Ameritas built-in benefits:** on the placed DInamic Cornerstone product (form 4601NC), Ameritas markets several built-in benefits:
 - **Good Health Benefit:** the elimination period drops 2 days for each consecutive claim-free policy year, down to a floor of 30 days (not available in NY).
 - **COBRA Premium Benefit:** reimburses COBRA premiums up to $1,000 a month for up to 18 months if a disability causes job loss.
 - **Benefit Advancement (nondisabling injury):** advances $500 of the base monthly benefit for an injury that needs medical or dental treatment but does not disable (state variations raise it to the lesser of 50% of base or $3,000 in FL, MT, ND, SC, SD, WY; not in NY).
 - **Presumptive Total Disability** that does NOT require the loss to be permanent or irrecoverable (an edge versus many carriers).
- **Ameritas product clarification:** DInamic Cornerstone (forms 4601NC / 4602GR) is the standard placed product; DInamic Foundation (forms 4501NC / 4502GR / 4503NCBOE) is the California product.
- **MassMutual Express DI Underwriting:** On Radius and Radius Choice, MassMutual offers an Express DI Underwriting path that waives the paramedical exam for eligible applicants up to age 50 (occupation class 3A and above, annual income of at least $30,000, on benefits up to $10,000 a month) and replaces it with a medical interview. The same program asks for no financial documentation from employed, non-owner applicants on benefits up to $10,000 a month (business owners: none up to $6,000, published requirements from $6,001 to $10,000), and runs the same streamlined path on Business Overhead Expense up to $20,000 a month with no financial requirements. Eligible applicants are identified during underwriting, and MassMutual reserves the right to request added requirements.
- **MassMutual + active-duty military:** In our experience, MassMutual is the only major that will
 write an individual disability policy for someone on active-duty military, through its dedicated program for
 military physicians and dentists. Military **physicians** qualify for a **25% discount** and military
 **dentists** for **10%** (**20% in CA and FL**).
- **MassMutual resident discounts:** resident and student group
 discount programs at MassMutual **commonly reach 20% for medical residents** and **10% for dental residents**,
 structured as noncancelable, portable multi-life/student-group discounts (the exact rate depends on program
 size and state; separate from the general AMA/institutional resident programs described on the resident pages).
- **The Standard + Lloyd's stacking:** on Platinum Advantage, an applicant who is at the
 max issue and participation may also apply for Lloyd's of London coverage without reducing The Standard policy
 benefit, a differentiator for the highest earners.
- **MassMutual Executive Select:** program for
 very high earners that, as of 2026, can cover up to roughly 50% of income and issue a monthly benefit as high
 as $60,000 for the most favorably classed professionals earning around $800,000+. **Excludes medical and
 dental occupations** (so the ceiling does not apply to most physicians/dentists) and is not available in every
 state (incl. CA/FL/PR); confirm fit case by case.
- **Financial strength:** Guardian/Berkshire
 Life **A++ (AM Best), Comdex 100**; MassMutual **A++, Comdex 98**; Principal **A+, Comdex 90**; The Standard
 **A, Comdex 84**; Ameritas **A, Comdex 82**.
- **Guardian contract strength:** In our view and experience,
 Guardian has the strongest contract of the five, for these concrete reasons: best default mental-health for
 qualifying occupations, true own-occ definition options, A++/Comdex 100.

---

### Northwestern Mutual

Seaworthy does not sell Northwestern Mutual products; NWM distributes only through its own financial
representatives. We review it because prospective clients routinely hold an NWM proposal and want it
compared against the independent market. Fair-balance applies to every use of these facts.

- **Distribution:** sold only through Northwestern Mutual's own advisors; not available through independent brokerages, so an NWM proposal cannot be comparison-shopped by the advisor presenting it.
- **Product/renewability:** individual disability income, TT policy series; non-cancelable to age 67 or 70 and conditionally renewable to age 80 (per NWM materials and published carrier comparisons, as of 2026).
- **Participating:** NWM disability policies are participating and eligible for annual dividends; NWM states DI dividends have been paid annually since 1971, with roughly $3 billion distributed on DI over the decade before 2022, and announced a record $9.2 billion total 2026 dividend payout, its 155th consecutive year of dividends. Dividends are not guaranteed, so an illustrated net-of-dividend premium can change; the guaranteed maximum premium is the contractual figure.
- **Definitions of total disability (the load-bearing fact; now verified against actual endorsement forms):** NWM offers medical professionals (physicians and dentists) elective definition options, per the policy endorsements on file: **True Own Occupation Option (form ICC21.TT.DI.TRU)**: totally disabled = unable to perform the substantial and material duties of the Regular Occupation; full benefit payable even while working in an occupation other than the Regular Occupation. **Medical True Own Occupation Option (form ICC21.TT.DI.MTO)**: adds a second pathway for a partially-able medical professional, who is Totally Disabled only if ALL THREE hold: (1) NOT gainfully employed in an occupation, (2) more than 50% of time in the Regular Occupation was devoted to direct patient care when disability began, and (3) unable to perform the duties that accounted for more than 50% of charges for direct patient care as evidenced by Billing Codes (CPT/ADA) for the 12 months before disability. KEY CONTRAST with Guardian's enhanced MD/DO definition: under NWM's MTO 50%-pathway the insured must NOT be working at all to collect the full benefit, while Guardian's enhanced definition pays the proceduralist full benefits even while practicing non-procedurally. Neither NWM option is available while the Conditional Right to Renew to Age 80 is in force. WHICH definition a proposal uses is elective and must be read off the illustration. (Sources: NWM endorsement forms ICC21.TT.DI.TRU/MTO (0221); NWM press release 2022-12-06 announcing the expanded choices.)
- **The older/standard "Medical Occupation Definition" (fair mechanics, per NWM's own 2011 materials and independent 2010 analysis):** NWM withdrew true own-occupation from the medical market in September 1997 (citing morbidity deterioration; per Lawrence Keller, Physicians News, April 2010) and marketed the Medical Occupation Definition instead. Its actual mechanics, per NWM's own piece (form 26-4255-79, 2011, CA): while unable to perform the usual occupation and working in ANOTHER occupation, earning up to 20% of pre-disability income preserves the FULL benefit; earnings between 20% and 80% proportionately reduce it. For a partially-able proceduralist it offered a choice typical own-occ policies lack: work and take a proportionate benefit, or NOT work and take the FULL benefit (typical own-occ pays partial benefits only while working). The independent critique (Keller 2010, quoting disability attorney Mark DeBofsky): the definition transforms claims that would be total under true own-occ into partial/residual claims unless the insured stops working or keeps other earnings under the thresholds. Both sides are accurate; date-stamp any use.
- **Mental/nervous:** commonly a 24-month limitation for physicians with a buy-up option to the full benefit period (secondary published reviews, as of 2026; confirm on the specific illustration).
- **Ratings:** AM Best A++ (Superior), the same top tier as Guardian and MassMutual (as of 2026).
- **Size:** NWM states it ranks #1 in disability income insurance. Printable AS ATTRIBUTED: "the largest individual disability income insurer in the US by direct premiums earned, per S&P Capital IQ Pro data cited by the company." Do not print as a bare unattributed #1.
- **Currency check:** independent 2026 reviews confirm the TT series and the elective True Own Occupation / Medical (own) Occupation definition architecture remain NWM's current product structure; published benefit periods are 5 years, 10 years, or to age 67/70 with 90-180 day elimination periods (secondary 2026 reviews; confirm on the illustration).

---

### Guardian Guaranteed Standard Issue (GSI) — Provider Choice 18GI

Guardian's employer-channel guaranteed-issue individual DI. Seaworthy does not place GSI (see internal note),
but clients and prospects routinely hold or are offered GSI through a hospital system or large employer and
ask how it fits with individual coverage, the same educational posture as the NWM section above.

- **What it is:** Guardian's Multi-Life Guaranteed Standard Issue program issues individual
 disability income policies (Provider Choice policy form 18GI) on an employer-sponsored basis. Eligible
 employees receive coverage at a guaranteed amount with **no medical underwriting**: health history,
 prior exclusions, and ratings do not affect issue at the GSI amount. (As of the current Guardian product
 materials, 2026.)
- **It is individual coverage, not group insurance:** each participant receives their own
 non-cancellable and guaranteed renewable individual policy on the Provider Choice chassis, distinct from an
 employer's group LTD plan. Benefit periods run 2-year, 5-year, 10-year, and to age 65/67/70; elimination
 periods 30 to 720 days; issue ages 18-75; occupation classes 6/6M down to 1/1M.
- **Own-occupation is available:** the definitions offered on 18GI include True Own-Occupation
 (plus two-year true with modified thereafter, modified own-occupation by endorsement, and two-year modified
 with any-occupation thereafter). A GSI policy is not automatically a weaker definition; the plan design
 chosen by the employer determines it.
- **Unisex, level premiums:** 18GI premiums are unisex and level.
- **Discounts:** GSI cases carry permanent multi-life discounts that scale with case size and
 funding (employer-paid vs voluntary), from roughly 15% on the smallest eligible cases to as much as 50% on
 the largest employer-paid cases. ("as of 2026")
- **Mental/substance limitation discounts:** plan designs electing a 24-month or 12-month
 mental/substance limitation earn premium discounts that scale with benefit period (roughly 5% to 15%);
 state variations apply (CA requires the 24-month limitation on new issues; some states replace 12-month
 with 6- or 24-month).
- **The catches worth naming:** (1) GSI is only available through an employer-sponsored multi-life
 case; an individual cannot buy it on their own. (2) Coverage above the GSI amount requires full medical
 underwriting (the "buy-up"), and rated/substandard offers are not made on GSI itself. (3) The participant does
 not choose the design; the employer's plan sets the definition of disability, benefit formula, and riders for
 the whole case.
- **GSI coverage IS portable.** The 18GI policy is an **individually owned, non-cancelable, guaranteed-
 renewable** individual DI policy (to age 65 for 2/5/10-yr and To-65 BPs; to age 67 for To-67/70 BPs). The
 participant owns it and **keeps it if they leave the employer** as long as premiums are paid; the carrier
 cannot cancel it or raise the rate, and the multi-life discount is permanent. The employer relationship
 matters at ISSUE (the no-underwriting guaranteed enrollment), not afterward. Do NOT frame portability as
 plan-design-dependent or uncertain — that was an error in the first draft.
 -
 The **Enhanced Portability Option** is a DISTINCT feature, not "whether the policy is portable": if the
 policyowner is no longer employed by the employer, they have **90 days from termination** to apply **once in
 their lifetime** for additional coverage up to a Maximum Benefit **without medical evidence**
 (financial/occupation underwriting only). It is a no-medical buy-up-on-leaving right, a strength, not a
 caveat. Published as a paraphrase on the GSI page 2026-07-20. [Src: DI Product Manual p.72, "Enhanced
 Portability Option".]
- **Where GSI shines (educational framing):** applicants with meaningful health history. Individual
 DI underwriting frequently modifies offers (per the 2026 book audit, roughly 4 in 10 CRNA applications draw
 an exclusion or rating); GSI issues at the guaranteed amount regardless, making it the cleanest path to
 coverage for someone who would otherwise face exclusions, ratings, or a decline.

## 4. Riders

- **Residual / partial disability:** income-loss threshold to trigger = **15%** (Guardian, MassMutual,
 Principal, Ameritas), **20%** (The Standard). All five pay a minimum ~50% early in a claim, then
 proportional to income loss, include a recovery benefit, and do **not** require a prior period of total
 disability. Range is **15-20%** (not "15-25%"); the "no prior total disability" feature is **universal**
 across these five (not a point of differentiation among them).
- **COLA:**
 Guardian = 3% compound, no cap (plus a CPI variant with a 3% floor / 6% cap, and a delayed variant);
 Principal = CPI compound, choice of 3% or 6% max; **MassMutual = 3% compound, NO cap** (fixed 3%, not
 CPI-indexed in-claim); Ameritas Cornerstone offers two COLA
 options, a 2-6% Compound option (CPI-U indexed, 2% minimum / 6% maximum compounded annually, with a catch-up
 feature, form COLA6C) and a 3% Compound option (CPI-U indexed, 3% maximum compounded annually, no minimum, with
 catch-up, form COLA3C); The Standard = CPI-indexed, 3% or 6% max, annually compound. All share a ~3% compound core but are not
 identical.
- **FIO / future increase option:** lets you raise coverage later without new medical underwriting.

---

## 5. Issue & Participation: income to max individual benefit

Verified 2026 from the MassMutual Issue & Participation chart + the Principal Underwriting Pocket Guide
(carriers track closely; treat as carrier-agnostic). **Use the Issue & Participation (total) column.**
The replacement ratio **declines as income rises**; it is NOT a flat 60%.

| Income | Max individual benefit (use) | ~% of income |
|---|---|---|
| $200K | ~$9,500 | ~57% |
| **$210K** | **~$10,000** | **~57%** |
| $265K | ~$12,400 | ~56% |
| $300K | ~$13,300 | ~53% |
| $350K | ~$15,000 | ~51% |
| $500K | ~$16,900 | ~41% |

- Hard class caps (regardless of income): MassMutual 5A/4A issue $35K, participation $40K w/ group LTD;
 Principal 6A/5A/4A/3A issue $35K for ages 18-60 ($20K only at 61+), participation $35K with other IDI and
 with group LTD.
- **Practical single-carrier max:** for a typical high earner a single carrier will issue
 around **~$20,000/month** for most high earners, and as high as **~$30,000/month** for some occupations,
 depending on occupation, income, and state; larger totals are possible by combining carriers.
- **Group LTD employer-plan cap** (separate concept): typically a **range of $10,000 to $15,000 a month**. The real market range is $10K-$25K, with about 95% of plans capping at $15,000 or less.

---

## 6. Book data: first-party

- **Exclusion-or-rating rate:** whole book **~28%**; **CRNA ~40% (highest)**,
 other professionals ~34%, **physician ~26%**, **dentist ~23% (lowest)**. ("Exclusion" = exclusion rider
 or a rating/extra premium.)
- **Most common exclusion category:** **mental/nervous (~43%)**, then musculoskeletal/spine
 (~26%), pregnancy/reproductive (~17%). Mental/nervous share within CRNA exclusions ~50%.
- **Reproductive exclusions:** ~9% of women's policies carry a pregnancy/
 reproductive exclusion; ~0 on men's.
- **Median age at issue:** whole book 36; CRNA 38 (oldest), dentist 34 (youngest).
- **Own-occ placed:** the vast majority of our clients carry a true own-occupation definition; true own-occ is standard for a specialized professional.
- **Elimination period:** 90-day is the most
 common choice, **82% of the placed book (2026 audit)**. 180-day is the OTHER mainstream
 structure: "roughly a third of our recent placements". The two are
 legitimate fits, neither superior; 180 fits clients with reserves comfortably past six months, premium
 savings can fund benefit/riders; the fit is decided per file with the advisor.
- **Benefit period:** to-age-65 on **87% of the placed book (2026 audit)**. Much of the remainder
 reflects what underwriting OFFERED (5-year-only offers), not buyer preference.
- **COLA:** **over 70% of placements in the last two years include a
 COLA rider (2026 book audit)**.
- **Gender mix:** CRNA ~59-60% female (majority), other 52%, dentist 48%, physician 43%.
- **Physician specialty mix:** internal medicine (including hospitalists),
 emergency medicine, family medicine, and anesthesiology are **among the most common physician specialties in
 the placed book** (2026 book review). Publish ONLY the qualitative "among the most common" framing; never the
 per-specialty policy counts.
- **CRNA premium / cost stats** (computed from the placed CRNA IDI book,
 2026 review; publish rounded + hedged + dated "as of the 2026 review," always framed as medians of policies as
 issued, NOT current new-business quotes; canonical page: /specialties/crna-disability-insurance-cost/):
 - Median premium ~$300/month (~$3,700/yr); middle half roughly **$225-$430/month**.
 - Premium as share of income: typically **1% to 2.5%**; middle half ~1.2%-2.3% (median just under 2%).
 - Unit cost per $1,000/month of benefit: median ~**$49/month**; by age at purchase ~$37 under 30,
 mid-$40s in the 30s, ~$50 early 40s, low $60s late 40s, ~$69 at 50+ (≈2x under-30 vs 50+).
 - Gender unit cost: women ~**$53** vs men ~**$42** per $1,000/month (~25% gap); frame with
 "individual DI is typically gender-rated" + the employer multi-life unisex-rate note.

---

## 6b. Individual DI and Social Security / SSDI interaction

- **Individual disability policies are independent of SSDI.** An individually owned, non-cancelable policy pays its stated monthly benefit regardless of Social Security Disability Insurance status; SSDI approval or denial does not affect it.
- **Group LTD plans commonly coordinate with SSDI.** Most employer group LTD policies have a Social Security offset: the plan pays the difference between its stated benefit and any SSDI award, meaning an SSDI award reduces the group LTD payment rather than stacking on top of it. This is one of the structural gaps between group and individual coverage.
- **Receiving individual DI benefits does not affect SSDI eligibility.** SSDI eligibility is based on work history, the disability standard, and earnings, not private insurance benefits. For tax treatment and eligibility details beyond this, refer to SSA.gov or a benefits attorney.

---

## 7. By occupation

### CRNA
- BLS median annual CRNA wage **$223,210 (May 2024)**. Well over double the mean for registered nurses.
- Top occupational disability risks (research-cited): musculoskeletal injury, mental health/
 burnout, substance use, fine-motor/nerve. (Burnout range 12-72%; SUD ~10-15%, similar to the general population.)
- **Mental/nervous for a CRNA:** ALL five major carriers limit a CRNA's
 mental/nervous (+ substance) claims to **24 months**. Nurse anesthetists sit in the high-risk group (with
 anesthesiology, ER, pain management, general dentistry, pharmacists and pharmacy technicians, certified
 anesthesiology assistants, and dental anesthesiologists) for which the cap is required, **including at
 Guardian**, whose "no time cap by default" applies to most OTHER occupations but NOT to CRNAs.

### Tech Professionals

- **Occupation class:** software engineers, developers, product managers, data scientists, and most
 office-based tech roles are **6A** (low-hazard cognitive work; Ameritas 6A = experienced professional, no
 hazards, $100K+ income). Tech sales classed "favorably" (varies by carrier). 6A is the top of the
 white-collar/general scale at 4 of 5 carriers, but **Principal has a "6A+" tier above 6A** (its "all others"
 scale = 6A+, 6A, 5A...), and medical occupations sit on a separate "M" scale. So 6A is NOT literally the
 single highest label. Tech is "one of the most favorable occupation classes" (or "a top occupation class").
- **Compensation:** high and equity-heavy (base + bonus + RSUs; sales = base + commission/OTE). The
 benefit is sized to total earned income, not base, because group LTD covers base only, caps, is taxable, and
 ends at job change. Document via ~2 yrs tax returns + vesting/bonus records. **How carriers treat RSUs/equity
 for income:** carrier income-UW docs define earned income as salary/wages/commission/bonus, and they do NOT
 name RSUs/equity as an insurable line (MM "Income Guidelines" = salary, wages, commissions, bonus, business
 income; Standard's "Equity" column = Business Equity Protector buy-out, NOT personal RSU; Principal = "earned
 income"). Bonus/commission are counted directly and averaged (MM bonus-averaging rules). VESTED RSUs are
 reported as W-2 wages, so that income generally counts when documented + recurring; carriers weigh one-time
 vesting differently; UNVESTED RSUs and unexercised options are NOT counted.
- **Mental/nervous:** tech is NOT in the high-risk
 occupation group, so **full-benefit-period M/N coverage IS available across ALL FIVE majors** (mechanism
 varies): **Guardian** full BP by default for non-high-risk classes;
 **Principal** full-term by DEFAULT (the 24-mo MNSA cap is an OPTIONAL ≤10% discount you can decline; required
 only CA/NY all, FL single-life, and the high-risk occupation list; tech not on it); **Ameritas** Cornerstone
 offers full max-BP M/N for classes 6A–3A (24-mo is an optional discount; GR product = 24-mo only); **The
 Standard** unlimited M/N for higher classes (24-mo is an optional 10% discount; required only for lower
 classes); **MassMutual** 24-mo built in, removable via Max Benefit Period Endorsement (+~15%, NOT in CA). The
 differentiator vs high-risk medical (anesthesiology/ER/pain/CRNA/general dentistry, who are FORCED into
 the cap) holds.
- **The Standard:** Preferred Occupation Discount up to 20% for favored office professions (engineers
 included). Multi-life is available.
- For a technologist, an any-occupation contract can collapse "you can still use a computer" into a
 denial, while a true own-occupation definition protects the actual technical or analytical role.
- Disability risks: repetitive strain/carpal tunnel, cognitive/neurological, back/neck/vision (sedentary),
 mental health/burnout.
- **Canonical equity-treatment (the RSU comp table):** base = counted directly; bonus + commission =
 counted, averaged ~2 yrs; vested RSUs = W-2 wages, counted when documented + recurring; one-time/cliff vest =
 weighed cautiously; unvested RSUs/RSAs, unexercised options, ESPP discount = NOT counted; dividends/cap-gains/
 investment = excluded (unearned). This table lives on \`tech-rsu-equity-compensation\` and is the source of
 truth for equity claims sitewide.
- **H-1B/visa:** all
 five majors consider work-visa applicants. **Guardian** considers foreign
 nationals holding H1B, L1, J1, G1, TN (green card holders need permanent-residence intent + SSN + US tax
 return). **Ameritas** green card = same basis as citizens; H-1B, J-1, L-1, O-1 case-by-case. **Principal**
 green card ≥1 yr = unrestricted; H1B/L1/J1/O1/TN case-by-case. **The Standard** green card usually no
 modification; H/J/L/O/TN recent-immigrant visas commonly get a Foreign Travel Exclusion. **MassMutual**
 non-US-citizens living full-time in US considered (Non-Citizen supplement form F6290); GSI requires citizen/
 permanent resident.

### Other Professionals
Custom CRNA-style hub at \`/specialties/professionals/\` (rebuilt from the directory page) + 5 spokes
(professionals-own-occupation, professionals-occupation-class, professionals-group-vs-individual,
professionals-quote-comparison, professionals-questions-before-buying), with the existing audience pages
(pharmacists, optometrists, physician-assistants, engineers, architects) linked in the hub's "Coverage by
Profession" group. The SECOND of the two deep hubs the
 Covers licensed/credentialed high earners OUTSIDE
medicine, dentistry, law, core business/finance, and tech (each has its own hub). Leads with allied health,
includes technical/licensed roles.
- **Pharmacists:** **the own-occupation / mental-nervous 24-month limitation is MANDATORY for pharmacists
 at both Principal AND Guardian** (Principal's required-limitation cluster includes ER, anesthesiology, pain mgmt,
 CRNAs, anesthesiology assistants, pharmacists; Guardian's mandatory mental/nervous high-risk group also includes
 pharmacists and pharmacy technicians; see §7 Principal + §8). A pharmacist wanting full-period own-occ or
 uncapped mental-health must weigh carriers.
- **MassMutual recent occupation-class upgrades:** in a
 recent occupational-class update, MassMutual raised several classes relevant to this group and to tech / business
 and finance: Nurse Practitioner to **4A**; Perfusionist to **4A**; Physician Assistant (primary care) to **5A**;
 Data Scientist, Information Security Specialist, and Computer Systems Analyst banded up to **5A/3**; and
 high-income finance roles (CFA, hedge-fund / VC / stockbroker) banded to **5A/3** at $250K+ income.
- **Technical (engineers, architects):** **The Standard Preferred Occupation Discount up to 20%** for
 favored office professions including engineers (same fact as the Tech section).
- **Other professionals: about 34% carry an exclusion or rating (2026 audit)** (§6). **Verified wage
 quotes used (quote bank):** pharmacists $137,480, optometrists $134,830, physician assistants $133,260 (all
 BLS OOH May 2024); plus SSA/IRS/BLS-LTD universals.

### Dentist
Custom CRNA-style hub at \`/specialties/dentists/\` (rebuilt from ProfessionLayout) + 6 spokes
(dentist-own-occupation, dentist-disability-risks, dentist-group-vs-individual, dentist-business-overhead-expense,
dentist-quote-comparison, dentist-questions-before-buying) + 7 dental specialty pages (oral-surgeons, orthodontists,
endodontists, periodontists, prosthodontists, pediatric-dentists, dentist-anesthesiologists). Canonical dental facts: dentists = **3D** at The Standard (qualifies for the
Own Occupation Rider; ADA-recognized specialty deemed the regular occupation); Guardian Specialty Own-Occupation
for dental classes; MassMutual recognizes ADA billing-code specialty and **upgrades 3D→4D with an AEGD/GPR
residency** (10% dental resident discount); Ameritas true own-occ base + **highest BOE limit ($100K/mo)**;
Principal most flexible, strong for surgical/dental. **All five = true own-occ for dentists** (the Standard non-own-occ exception is CRNA-only, not dental). PUBLIC book stats: dentist exclusion/rating **~23% (lowest)**, median
age at issue **34 (youngest)**.

### Dental Hygienist

**A dental hygienist is a distinct occupation, NOT a dental specialty.** Do not group hygienists with the DDS/DMD specialty pages (oral surgeons, orthodontists, etc.); they carry a different license, a much lower occupation class, and a materially narrower carrier market. Operator ruling 2026-07-27: hygienists ARE a market worth serving (the converting lead that prompted this was in the $200-250K income band), but the page must serve the high-earning end without generalizing hygienist income upward — the BLS median sits far below that, so never imply $200K+ is typical.

- **Occupation class at Ameritas: 2M.** The guide lists "Dental Hygienist, Dental Assistant" as 2M and defines the class as healthcare occupations requiring more physical activity, and other occupations where claims experience has not been as favorable as class 3M; registered and practical nurses and podiatrists are the guide's other named examples. Scope any use "per the mid-2026 producer guides."
- **Own-occupation availability is the load-bearing fact. TRUE own-occ is NOT available at 2M.** Ameritas offers three definitions of total disability: **OO** (own occupation for the length of the benefit period), **NW** (own occupation **and not working** for the length of the benefit period), and **P2** (two-year own occupation, then any reasonable occupation). The availability-by-class table restricts **OO to 6A, 6M, 5A, 5M, 4A, 4M, 4P, 4D, 3A, 3M**. At **2A/2M the options are NW and P2 only** (NW alone on the 1-year GR form). So the placeable contract is **NW to age 65** (issue ages 18-62; to-67 also available at 18-64). **This IS own-occupation coverage** — the definition is measured against the insured's own occupation — but it requires not working in another occupation to collect. **Never call it "true own-occupation."** Also: the guide's specialty own-occupation language is included for physicians and dentists, and does not extend to hygienists.
- **Mental/nervous is capped at two years and the cap is NOT elective at this class.** Full-benefit-period M/N on noncancelable policies is available only to **6A-3A, 6M-4M, and 4D**; 4P requires the two-year limitation; it is unavailable to classes A, B and M. **2M is absent from the full-BP list, so a hygienist takes the 24-month limitation.** Guaranteed renewable policies are two-year-only for every class. (Mechanically the same 24-month outcome as the high-risk medical group, but for a different reason — class-based, not the occupation-risk list.)
- **Issue and participation limits at 2A/2M: $8,000, with no stacking room.** Ages 18-60: maximum issue $8,000 (individual pay and employer pay), and maximum participation **also $8,000** both with other individual DI and with group LTD. Unlike higher classes where participation exceeds issue, there is no room to stack a second carrier. Ages 61+: $10,000 maximum issue regardless of class. **This is the most useful fact for a high-earning hygienist** — at $200-250K it is roughly a 38-48% replacement ceiling, which reframes the decision from "how much can I get" toward securing the maximum early. Operator estimated 8-9K from memory; the guide confirms $8,000 flat.
- **The market is narrow: two realistic options.** Ameritas modified own-occ (NW) to age 65 is the intended placement. **Lloyd's of London** (surplus lines) writes a **true own-occupation contract for a 3-year benefit period** as the alternative. The honest framing is a tradeoff between definition strength and benefit duration, not a clear winner. Operator note: the Lloyd's option would not be sold often.
- **Approved existing framing**: hands-dependent clinical work deserves an occupation-specific definition; carriers classify hygienists differently than dentists; the market is narrower and pricing differs; individual coverage is available.

### Physician
Custom CRNA-style hub at \`/specialties/physicians/\` (rebuilt from the directory page) + 7 spokes
(physician-own-occupation, physician-disability-risks, physician-mental-health, physician-group-vs-individual,
physician-quote-comparison, physician-benefit-sizing, physician-questions-before-buying) + the existing physician
specialty pages (surgeons, anesthesiologists, obgyn, nephrologists, geriatricians, infectious-disease,
sports-medicine; more to add over time). Canonical physician
facts: all five = true own-occ for physicians; specialty recognition differs (Guardian **Enhanced Medical
Specialty MD/DO** surgical-income definition for proceduralists; MassMutual **CPT billing-code** specialty
recognition; The Standard **ABMS/AOABOS** deeming, Own Occupation Rider at 3P+; Ameritas/Principal as placed,
Principal most flexible). Classes: Guardian 5M/4M/3M (the physician ceiling is 5M; no physician specialty is 6M
);
MassMutual 5P/4P/3P; Standard 5P / 4S / 4P / 3P (4S is The Standard's dedicated
surgical/interventional class: neurosurgeon, ophthalmologist, plastic/cardiothoracic surgeon, interventional
cardiologist). **Full-benefit-period
M/N available to MOST physicians including surgeons**; 24-mo cap forced only on the high-risk group
(anesthesiology, ER, pain-mgmt, CRNA, general dentistry, plus pharmacists, certified anesthesiology
assistants, and dental anesthesiologists at Guardian). PUBLIC book stats: physician exclusion/rating **~26%**,
mental/nervous most common (~40% of physician exclusions), median age at issue **36**.

#### Physician deep facts

**Occupation classes by specialty (cross-carrier map).** Class assignments are current as of the mid-2026
producer guides; carriers revise classes periodically, so a current quote is the only reliable read.
- **The same physician specialty is classed very differently across the five majors**, and class is a
 primary premium driver. Marquee divergences: an **orthopedic surgeon** is 5M at Ameritas but 3M at Guardian and
 Principal, 3P at MassMutual and The Standard (a roughly two-class spread); a **psychiatrist** is 5M at Ameritas
 vs 4M/4P elsewhere; an **ophthalmologist** is 3P at MassMutual but 5M at Principal and Ameritas and 4S at The
 Standard; a **pediatrician** is Principal's ONLY 6M physician specialty (its top medical class); **pain
 management** runs from 2M+ at Principal (its lowest physician class) to 5M at Ameritas.
- **Guardian classes (May 2025 guide):** 5M = the internal-medicine family (internist, family practice,
 pediatrician, hospitalist, pathologist, gastroenterologist, oncologist, pulmonologist, endocrinologist);
 4M = psychiatrist, neurologist, **neurosurgeon**, ophthalmologist, ENT, urologist, dermatologist, cardiologist,
 radiologist; 3M = all other surgeons, anesthesiologist, ER, OB/GYN, orthopedic and plastic surgeons, pain
 management. Notable: a neurosurgeon (4M) classes better than general or orthopedic surgeons (3M), and family
 practice/internal medicine were UPGRADED from 4M to 5M between the 2022 and 2025 guide editions. Classification
 follows ABMS board certification; a physician with multiple specialties is classed on the more hazardous one.
- **Principal classes (ICC22-800):** pediatrician 6M; oncologist and neurologist 5M+; internal-medicine
 family, ophthalmologist, physiatrist 5M; cardiologist, dermatologist, psychiatrist, neurosurgeon,
 cardiovascular/vascular surgeons, urologist, ENT, OB/GYN 4M; general/orthopedic/plastic surgeons,
 anesthesiologist, ER 3M; pain management 2M+. Radiology and nuclear medicine split invasive (4M) vs
 non-invasive (5M). Sub-specialty is not inherited: a pediatric hospitalist classes as a hospitalist.
- **MassMutual classes (Radius Choice 21):** 5P/1 (best physician pricing tier) = family practice,
 internist, pediatrician, hospitalist, oncologist, pulmonologist, allergist; 5P = non-invasive cardiology and
 dermatology, endocrinologist, gastroenterologist, neurologist, pathologist; 4P = psychiatrist, ENT, urologist,
 invasive radiology, critical care, infectious disease; 3P = anesthesiologist, ER, OB/GYN, ophthalmologist,
 orthopedic/thoracic/cardiovascular/neuro surgeons, interventional cardiology, pain management, and residents or
 students until a specialty is declared. Several specialties split invasive vs non-invasive within one name.
- **Ameritas Cornerstone classes:** 6M includes the internal-medicine family plus dermatologic surgery,
 radiologists, critical care, and neurologists (generous vs peers); 5M = cardiologists, **neurosurgeons,
 orthopedic and hand surgeons, ophthalmologists, ENT, urologists, psychiatrists, pain management**; 4M =
 general, cardiovascular, plastic, and colorectal surgeons; 4P (a Cornerstone-only class) = anesthesiologists,
 ER physicians, OB/GYNs, reproductive endocrinologists. With multiple occupations the lowest class controls.
- **The Standard classes (Platinum Advantage):** 5P = non-procedural specialists (gastroenterology,
 family medicine, internal medicine, pediatrics, neurology, diagnostic radiology, pathology, oncology); 4P =
 dermatology, psychiatry, non-interventional cardiology, critical care; 4S = the dedicated surgical/
 interventional class (neurosurgery, plastics, ophthalmology, ENT, urology, general surgery, cardiothoracic,
 interventional cardiology and radiology, colorectal); 3P = higher-risk practices (anesthesiology, EM,
 **orthopedic and hand surgeons**, OB, GYN, reproductive endocrinology, anesthesia/EM-certified pain medicine).
 Certification splits: pain medicine is 3P with an anesthesia/EM primary certification, otherwise 4P; sports
 medicine runs 5P/4P/3P by primary certification. With multiple occupations the riskiest one sets the class.

**Own-occupation mechanics for physicians (contract-verified).**
- **Guardian surgical-income enhancement:** for an MD/DO earning **more than 50% of income from
 performing surgical procedures**, Guardian deems total disability when the physician can no longer perform
 surgical procedures, even while gainfully employed in the practice or elsewhere. "Surgical Procedures" means
 incision-with-instruments interventions regularly performed in the 12 months before disability (injections
 alone do not count). A parallel **Hands-on Patient Care** enhancement applies the same 50% mechanic to
 clinicians. Guardian applies three definition tiers, and medical classes receive the full Enhanced Medical
 Specialty tier when eligible.
- **Guardian Enhanced Medical Specialty prerequisites:** the enhanced tier requires the policy to carry
 a Basic or Enhanced Partial rider and to be issued without Graded Lifetime; a physician who does not qualify
 still holds the standard true own-occupation definition with specialty deeming.
- **MassMutual billing-code deeming:** the Own Occupation Rider deems a medical specialty the insured's
 occupation when "the main duties of that specialty are verified by the Billing Codes" (CPT) "for the 12 months
 before Disability began." **No percentage-of-billing threshold exists in the contract.** The California rider
 version is broader still: its total-disability definition does not require working in another occupation.
- **The Standard's ABMS deeming lives in the BASE policy**, not only the rider: a physician who has
 limited practice to a single ABMS/AOABOS-recognized specialty has that specialty deemed the Regular Occupation,
 with no board-certification, income-percentage, or time-percentage test in the contract language.
- **Principal specialty recognition (contract wording):** a single professionally recognized specialty
 in medicine, within the scope of the license, is considered the own occupation; included on every policy at no
 extra cost. **Principal's True Own Occupation definition is available across its physician classes, including
 2M+ occupations**.
- **Ameritas offers a P2 definition tier** (two-year own-occupation, then any reasonable occupation)
 alongside its true own-occupation options; the cheaper tier is worth knowingly declining or accepting.
- **Residual is mandatory for physicians at Ameritas:** medical classes 6M-3M cannot buy Cornerstone
 without a residual rider. Its Enhanced Plus residual uses a 15% earnings-loss threshold, pays a 75%+ loss as
 total disability, and includes a 100% income-replacement return-to-work incentive for the first three months.

**Residents, fellows, and new physicians (all five compared).**
- **Every major carrier writes residents with no income documentation and disregards group LTD** for
 the training-to-new-practice window; the published limits differ: Guardian residents $5,000/mo and fellows/new
 physicians $7,500 (FIO to $22,500, a 3x multiple vs the standard 2x); Principal $5,000 residency years and
 $7,500 for final-6-months residents, fellows, and first-2-years physicians (psychiatrists carved out at
 $6,500); MassMutual residents $7,500 and first-2-years physicians $8,000; Ameritas residents $7,500 (FIO
 $22,500) and entering-practice $8,500 (FIO $21,500); The Standard final-year residents, fellows, and
 new-in-practice $8,000 ($5,000 earlier years). Medical students in the last two school years can typically buy
 $1,500-$2,500/mo.
- **Resident discounts:** Guardian 10% (through 180 days post-graduation); Principal 20% resident
 multi-life (gender-specific; apply in the graduation year); MassMutual student/multi-life programs commonly
 reaching 20% (program-dependent); Ameritas 15% with NO minimum lives, and **attending staff physicians at
 medical teaching hospitals are also eligible**; The Standard 15% Residency Multi-Life from program acceptance
 to 180 days after training.
- **Exam and increase concessions for young physicians:** The Standard requires no blood work,
 urinalysis, or exams at ANY benefit amount for ages 18-50; Ameritas underwrites physicians within 180 days of
 residency completion to $8,500 with no exam, and with a signed contract to the contract salary with no exam at
 any amount, plus up to two accelerated increases in the first three policy years; Principal's Maximize Your
 Benefit rider allows increases to full limits on income alone (no labs) in its first three years; The Standard
 waives its 75% Benefit Increase Rider rule for residents (buy as little as $1,000/mo and keep increase rights)
 and offers an accelerated increase within 12 months post-training; signed employment contracts unlock full
 limits up to ~6 months before starting at Principal, MassMutual, and The Standard.
- **Student loan riders:** MassMutual $100-$2,500/mo with a 10- or 15-year term that runs from the
 POLICY date (issue ages 18-40 both terms, 41-45 ten-year only), paying the lesser of the actual loan obligation
 or the selected maximum; The Standard's version caps at $2,500/mo for physician classes vs $1,500 for office
 classes; Guardian allows $2,500/mo for MD/DO regardless of class. Average medical school debt runs about
 $205,000-$207,000 (AAMC 2022/2023).

**Mental/nervous for physicians (the five-carrier picture).**
- **The mandatory 24-month lists are nearly identical across carriers** (anesthesiology, ER, pain
 management, CRNAs, plus pharmacists and general dentists at some), and every other physician specialty has a
 full-benefit-period path: Guardian offers a choice of 12-month, 24-month, or UNLIMITED M/N for non-high-risk
 physicians (a future-increase policy exercised from an unlimited policy keeps unlimited); Principal's rider is
 optional for psychiatrists, surgeons, and internists (electing the cap earns ~10% at long benefit periods,
 with a rarely documented nuance: after 24 months of substance-abuse benefits a distinct mental/nervous
 condition can draw up to 12 more months); MassMutual's cap is removable via the Maximum Benefit Period
 Endorsement for roughly 15% extra premium (not in CA; not available to the high-risk list; a 10% employer-paid
 version exists for 20+ life cases); Ameritas Cornerstone classes 6M-4M choose the cap (10% discount) or full
 period; The Standard's limitation is optional with a 10% discount for 5P/4P/4S and required for 3P/2P.
 California requires the limitation on all policies at every carrier; Vermont mandates full coverage on longer
 benefit periods at several.

**Physician income and benefit limits.**
- **Issue caps differ by carrier AND by specialty tier:** Guardian and MassMutual cap all physician
 classes at $30,000/mo issue ($35,000 with group LTD; Guardian reaches $42,000 when all group LTD benefits are
 taxable); MassMutual's 2025 update raised physician classes 50%, from $20,000 to $30,000; Ameritas physician
 classes cap at $30,000; **Principal splits by tier: $30,000 for 6M/5M/4M but $20,000 issue for 3M/3M+/2M+**
 (surgeons, anesthesiology, ER, pain management), participating to $30,000/$35,000; The Standard's physician
 classes cap at $30,000 ($35,000 with group LTD) through age 55. Sample individual-pay ladders cluster tightly
 across carriers: roughly $13,000-$13,700/mo at $300K income, $18,000 at $500K, $28,000 at $1M.
- **Unearned income can reduce or block coverage:** carriers typically disregard unearned income up to
 about 50% of earned income and offset above that; applicants with substantial unearned income can be declined.
- **Locum tenens and 1099 physicians:** Guardian accepts first-year 1099 contracts with a 50% expense
 ratio (as low as 25% at underwriter discretion) and treats locum contracts of 6+ months under that rule;
 shorter locum work generally needs documented income stability plus a year of full-time history. Physician
 recruitment agreements are commonly credited at up to 60% of the contract amount.
- **Part-time physicians are insurable at Principal:** 20-29 hours/week with $40,000+ income, all
 states. Most carriers otherwise require 30+ hours.
- **Gender pricing nuance:** Principal applies gender-specific rates to physicians even in multi-life
 arrangements (its non-medical multi-life is gender-neutral), and its 20% resident discount is gender-specific.
 Material when a female physician compares carriers.

**Programs, discounts, and features worth naming.**
- **Occupation discounts for physicians:** Guardian's Preferred Occupation Discount (10%) covers 5M
 board-certified pulmonologists, 4M internal-medicine physicians (except rheumatologists), 4M board-certified
 radiologists and radiation oncologists, and 3M board-certified surgeons EXCEPT orthopedic surgeons; The
 Standard offers 5% for select 5P specialties (diagnostic radiology, gastroenterology, medical oncology,
 neonatology, neurology, pediatrics, rheumatology); Ameritas applies a 5% lower state pricing factor to
 non-surgical physicians (6M/5M) in ten states (GA, IL, IN, IA, KS, MN, MO, NE, OH, WI).
- **Built-in extras with physician relevance:** Ameritas Cornerstone's presumptive total disability
 does not require the loss to be permanent, its Good Health Benefit trims the elimination period two days per
 claim-free year (floor 30), COBRA reimbursement runs to $1,000/mo for 18 months, and transplant-donor and
 cosmetic-surgery disabilities are treated as sickness; Principal builds in a transplant-surgery benefit;
 The Standard's Platinum Advantage pays pregnancy/childbirth disabilities after the first 90 days only when due
 to complications, and its physician business is substantial: physicians buy more than half of all IDI policies
 The Standard sells, with $170.1M paid in 2025 and $1.407B over the past ten years, including published
 specialty-own-occ paid claims (an OB-GYN paid total disability while working as a clinical-trial reviewer; an
 anesthesiologist paid total while working as an assistant professor).
- **Ameritas physician BOE:** $100,000/mo maximum (12-month benefit period) with a Substitute Salary
 Expense benefit up to $50,000/mo, and a BOE EZ App to $25,000/mo with no mini-exam (ages 18-50).
- **License loss alone is not a disability:** carriers exclude claims where the only barrier to work is
 a suspended, revoked, or surrendered license (exact wording verified at Ameritas and The Standard; the pattern
 is standard across the industry), unless the loss results directly from sickness or injury.
- **Sourced physician claim statistics (MassMutual, 1972-2022):** musculoskeletal 24%, mental disorders
 14%, injury 11%, circulatory 9%, nervous-system 9%, cancer 8%; most disabilities are caused by illness, not
 injury; MassMutual's average DI claim runs about four years, with $5.8B paid 2005-2023.

### Attorney
Placeholder: same structure as CRNA/dentist/physician. The Standard deems "trial attorney" a specialty under its
Own Occupation Rider (citable carrier fact). (Slot future facts here.)

---

## 8. AANA Member Advantage plan

Verified from the specimen (form HGN-5571 03/25, New York Life, Group Policy G-29285-0, admin Hagan).
- **Own-occupation** ("regular occupation… not just any job"), NOT generic nursing, BUT benefit is
 **reduced by 50% of income earned in another occupation** (own-occ with an offset).
- Member-paid → **benefits tax-free**; **medically underwritten** (not auto-issue).
- Benefit **$1,000-$12,000/mo**, up to 70% of income, total DI across all companies under $20,000/mo;
 $5,000 max if practicing <1yr; **drops to $1,000/mo at age 65**.
- Waiting 61/91/180; benefit periods 5yr/10yr/to-65.
- **Residual requires a prior covered total disability** for the same condition (weaker than individual,
 which pays on income loss alone).
- **Mental/nervous + substance capped at 12 months.**
- COLA optional (up to 6% CPI-U, capped 2x).
- Premiums are **age-banded and rise steeply with age, not level**: on the current AANA rate schedule, a CRNA's monthly premium in the early 50s runs roughly **3 to 4.5 times** the premium in the 30s, and keeps climbing through every five-year band. An individually-owned non-cancelable policy instead locks a level premium at issue to age 65.
- Portable to age 70 but **tied to AANA membership**.
- An **individual policy is the core**; AANA is not a substitute.

---

## 8b. AMA & ADA plans

**AMA plan (New York Life, group policy G-30639-0):**
- Premiums increase at every age bracket (on renewal date); rates adjustable class-wide. Renewal requires:
 physician actively at work, US resident, under 75, NOT retired, premiums paid, group policy in force,
 AMA continues sponsoring. License revocation (criminal/ethical/gross malpractice) terminates. Layoff
 continuation 90 days.
- Base Own-Specialty definition pays only while NOT gainfully employed; True-Own-Specialty = paid upgrade.
- Residual requires a prior covered total disability + 20% loss.
- FIO: one-time, within 3 years of issue, before age 40. M/N: 24 mo before 69. COLA: paid rider ~15% of
 premium, skips first claim year. Caps: $15K/mo under 55, $5K for 55-60; combined 66 2/3% / $30K.
- Waiting period (2/3/6/12 mo) is NOT a usable gap (2-mo option is shorter than the 90-day standard).
- Membership not required; 10% member credit reviewed annually.

**ADA plan (Protective, forms IP-P 7-20 / IP-P-NY 12-20; cert IP-C-NY 12-20 on file):**
- Premiums: attained-age 5-yr bands AND Protective may change group rates as often as once / 12 months
 (180-day notice to the Association, not the member). Coverage Lock-in locks features, NOT price.
- Certificate termination: no longer an active ADA member; retires; active military >30 days; age 75;
 Association terminates the group policy. "Actively Working Full-Time" = 20+ hrs/week (eligibility +
 continued coverage). Group certificate, not an owned policy.
- Base residual pays only AFTER a prior total disability. Residual Plus (no prior total, non-consecutive
 waiting-period days, billables-based early loss): under-50 applicants only, renewable through 64,
 recovery benefit max 3 months. Individual contrast: income-loss-alone, 15-20% trigger, recovery
 commonly continues while loss persists (Principal's recovery benefit runs to the end of the benefit period).
- Cap $15,000/mo; FIO adds $1K/yr to max $5K, always INSIDE the $15K plan max. COLA: CPI, 9%/yr cap,
 option renewable through 59. M/N: full benefit period; substance limited to 12 months (half the individual
 24). True own-occ claim standard applies; gaps are structural.
- ADA BOE certificate: max insured amount $25,000/mo across all BOE coverage; same group rate-change
 structure. Individual BOE: roughly $50,000 to $60,000 majors (Guardian to $60K), $100K Ameritas (§3).
- Marketing page says ADA membership earns a "premium credit discount," but the cert terminates coverage
 on membership loss; certificate governs → membership-required stands.

---

## 11. External-fact citations
- **BLS OEWS May 2024**, Nurse Anesthetists 29-1151: median annual wage **$223,210**; Registered Nurses 29-1141 median **$93,600**; Software Developers 15-1252 median **$133,080**.
- **IRS Pub 525**: employer-paid group DI premiums → benefits taxable; after-tax individual premiums →
 benefits tax-free.
- Musculoskeletal/burnout/SUD: PMC/AANA/PubMed (see crna-disability-risks for exact cites). BLS blocks
 automated fetch; verify via archive or secondary sources.

---

## 12. Credibility & trust signals

Verified proofs for when a visitor questions trust or legitimacy. Use ONE at a time, matched to the doubt, never a list. Scale is qualitative only; never a specific client or policy count.

- **Independent brokerage, since 2011, 15+ years** placing individual disability insurance for high-income professionals. Specialized in income protection for high earners, not a generalist shop.
- **Licensed and active in all 50 states**; appointed with the five major DI carriers (Guardian, Principal, MassMutual, Ameritas, The Standard), plus Lloyd's of London for cases the majors cannot place.
- **BBB Accredited, A+ rating.** https://www.bbb.org/us/ca/san-juan-capistrano/profile/disability-insurance/seaworthy-insurance-1126-1000167755 (listed under the legal name, Physician's Disability Insurance Agency, same firm).
- **5-star rating on Google.** https://seaworthy.io/reviews.
- **How the firm is paid:** independent and carrier-neutral; paid by carrier commissions when a policy is placed (the standard across the brokerage industry); no fee to the client for the comparison or the placement; recommendations made on contract language and fit, not commission. Every quote is compared across all the major carriers on the actual policy language, not price alone.
- **Published transparency:** methodology https://seaworthy.io/methodology/, editorial policy https://seaworthy.io/editorial-policy/, sources https://seaworthy.io/sources/. How the firm works and where its numbers come from.
- **Named, 20+ year team** with real bios: Toby Lason (https://seaworthy.io/team/toby-lason/, https://www.linkedin.com/in/tobylason/) and Phil Neujahr (https://seaworthy.io/team/phil-neujahr/, https://www.linkedin.com/in/philneujahr/), co-owners, plus licensed advisors and a dedicated case manager.
- The firm has placed individual disability coverage for thousands of professionals, including hundreds of CRNAs, physicians, and dentists, over 15+ years.
- **Brand disambiguation:** Seaworthy Insurance is an independent disability insurance brokerage, founded in 2011 as Physician's Disability Insurance Agency and rebranded in June 2026. It is not affiliated with GEICO Marine Insurance Company, the boat insurer that operated under the name "Seaworthy Insurance Company" until GEICO renamed it in 2015. Seaworthy Insurance does not sell marine or boat insurance.

---
`;
