// Canonical occupation list — server-side copy for lead classification.
// GENERATED from astro-site/src/data/occupations.js — keep the three copies in sync
// (astro-site master + chat-worker + mcp-worker) whenever occupations change.
// Values mirror the Salesforce General_Occupation__c picklist API Names
// (web-to-lead field 00NRl000003Xrwf) on Lead and Account.

export const OCCUPATIONS: readonly string[] = [
  "Account Executive",
  "Accountant / CPA",
  "Actuary",
  "Acupuncture",
  "Addiction Medicine Physician",
  "AI / Machine Learning Engineer",
  "Air Traffic Controller",
  "Airline Pilot",
  "Allergist / Immunologist",
  "Anesthesiologist",
  "Anesthesiology (Dental)",
  "Architect",
  "Attorney",
  "Attorney (Partner / Owner)",
  "Audiologist",
  "Bariatric Surgeon",
  "Board Member",
  "Breast Surgeon",
  "Business Owner",
  "Cardiac Surgeon",
  "Cardiologist (Electrophysiology)",
  "Cardiologist (Interventional)",
  "Cardiologist (Non-Invasive)",
  "Cardiothoracic Surgeon",
  "CEO",
  "CFO",
  "Chief Information Officer (CIO)",
  "Chief Operating Officer (COO)",
  "Chief Revenue Officer (CRO)",
  "Chief Technology Officer (CTO)",
  "Child & Adolescent Psychiatrist",
  "Chiropractor",
  "Civil Engineer",
  "Clinical Psychologist",
  "Cloud Engineer",
  "Colorectal Surgeon",
  "Commercial Banker",
  "Commercial Pilot",
  "Commercial Real Estate Broker",
  "Construction Manager",
  "Consultant",
  "Content Creator / Influencer",
  "Corporate Pilot",
  "Critical Care Physician",
  "CRNA",
  "Cybersecurity Professional",
  "Data Engineer",
  "Data Scientist",
  "Dental Hygienist",
  "Dental Students",
  "Dentist (Owner)",
  "Dermatologist (Diagnostic)",
  "Dermatologist (Interventional)",
  "Dermatologist (Mohs)",
  "DevOps / Infrastructure Engineer",
  "Economist",
  "Electrical Engineer",
  "Emergency Medicine Physician",
  "Endocrinologist",
  "Endodontist",
  "Engineering Director",
  "Engineering Manager",
  "ENT Physician",
  "Enterprise Account Executive",
  "Executive / Senior Leader",
  "Executive Recruiter",
  "Family Medicine Physician",
  "Financial Advisor / Wealth Manager",
  "Financial Product Sales",
  "Franchise Owner",
  "Gastroenterologist",
  "General Contractor",
  "General Counsel",
  "General Dentist",
  "General Dentist (AEGD)",
  "General Dentist (GPR)",
  "General Practice",
  "General Surgeon",
  "Geriatrician",
  "Gynecologic Oncologist",
  "Gynecologist",
  "Hand Surgeon",
  "Hedge Fund Professional",
  "Hematology / Oncology Physician",
  "Hospitalist",
  "Independent Consultant",
  "Infectious Disease Physician",
  "Insurance Agent / Broker",
  "Insurance Underwriter",
  "Internal Medicine Physician",
  "Investment Banker",
  "IT Manager / Director",
  "Judge",
  "Lobbyist",
  "Management Consultant",
  "Managing Director",
  "Managing Partner",
  "Maternal-Fetal Medicine Physician",
  "Mechanical Engineer",
  "Medical Device Sales",
  "Medical Oncologist",
  "Medical Students",
  "Neonatologist (Diagnostic)",
  "Neonatologist (Interventional)",
  "Nephrologist (Diagnostic)",
  "Nephrologist (Interventional)",
  "Neurologist",
  "Neurosurgeon",
  "Nuclear Medicine Physician",
  "Nurse Midwife (CNM)",
  "Nurse Practitioner",
  "OB/GYN",
  "Occupational Medicine",
  "Occupational Therapist",
  "Operating Partner",
  "Ophthalmologist (Diagnostic)",
  "Ophthalmologist (Interventional)",
  "Optometrist",
  "Oral Surgeon",
  "Orthodontist",
  "Orthopedic Surgeon",
  "Orthopedic Surgeon (Hand)",
  "Orthopedic Surgeon (Spine)",
  "Osteopaths",
  "Otolaryngologist",
  "Pain Management Physician",
  "Palliative Medicine Physician",
  "Patent / IP Attorney",
  "Pathologist (Diagnostic)",
  "Pathologist (Interventional)",
  "Pediatric Anesthesiology",
  "Pediatric Cardiology",
  "Pediatric Critical Care",
  "Pediatric Dentist",
  "Pediatric Emergency Medicine",
  "Pediatric Endocrinologist",
  "Pediatric Gastroenterology",
  "Pediatric Hematology/Oncology",
  "Pediatric Nephrology",
  "Pediatric Neurology",
  "Pediatric Pulmonology",
  "Pediatric Surgeon",
  "Pediatrician",
  "Perinatology",
  "Periodontist",
  "Petroleum Engineer",
  "Pharmaceutical Sales",
  "Pharmacist",
  "Pharmacist (Owner)",
  "Physical Medicine & Rehabilitation Physician",
  "Physical Therapist",
  "Physical Therapist (Owner)",
  "Physician Assistant",
  "Physician Executive",
  "Plastic Surgeon",
  "Podiatrist (Diagnostic)",
  "Podiatrist (Interventional)",
  "Portfolio Manager",
  "Preventive Medicine Physician",
  "Primary Care",
  "Private Credit Professional",
  "Private Equity Professional",
  "Product Designer (UX/UI)",
  "Product Manager",
  "Professional Speaker",
  "Property Manager",
  "Prosthodontist",
  "Psychiatrist",
  "Pulmonary / Critical Care Physician",
  "Pulmonologist",
  "QA / Test Engineer",
  "Radiation Oncologist (Diagnostic)",
  "Radiation Oncologist (Interventional)",
  "Radiologist (Diagnostic)",
  "Radiologist (Interventional)",
  "Radiologist (Neuro)",
  "Real Estate Developer",
  "Real Estate Fund Manager",
  "Real Estate Investor",
  "Real Estate Syndicator",
  "Registered Nurse",
  "Reproductive Endocrinologist",
  "Residential Real Estate Agent",
  "Retina Specialist",
  "Rheumatologist",
  "Sales Manager / VP of Sales",
  "Sleep Medicine Physician",
  "Software Engineer",
  "Solutions Architect",
  "Speech-Language Pathologist",
  "Spine Surgeon",
  "Sports Medicine Physician",
  "Startup Founder",
  "Supply Chain / Logistics Professional",
  "Surgical Oncologist",
  "Technical Program Manager",
  "Technical Sales Engineer",
  "Trader",
  "Transplant Surgeon",
  "Trauma Surgeon",
  "Urgent Care",
  "Urogynecology",
  "Urologist (Diagnostic)",
  "Urologist (Interventional)",
  "Vascular Surgeon",
  "Venture Capital Professional",
  "Veterinarian (Large Animals)",
  "Veterinarian (Small Animals)",
  "Veterinarian (Surgery)",
  "VP of Engineering",
  "Web Developer",
  "Wound Care",
] as const;

// Common variants agents and chat visitors use for canonical occupations.
const ALIASES: Record<string, string> = {
  "nurse anesthetist": "CRNA",
  "crna / nurse anesthetist": "CRNA",
  "certified registered nurse anesthetist": "CRNA",
  "colorectal surgery": "Colorectal Surgeon",
  "ob-gyn": "OB/GYN",
  "obgyn": "OB/GYN",
};

// Case-insensitive match of a free-form profession against the canonical list.
// Returns the canonical value, or null when there is no exact/alias match
// (callers then file the lead as "Other" and preserve the raw text).
export function matchOccupation(raw: string): string | null {
  const q = (raw || "").trim().toLowerCase();
  if (!q) return null;
  if (ALIASES[q]) return ALIASES[q];
  for (const o of OCCUPATIONS) if (o.toLowerCase() === q) return o;
  return null;
}
